CREATE TABLE expenses( _id INTEGER PRIMARY KEY AUTOINCREMENT, date STRING NOT NULL, amount REAL NOT NULL, tag INTEGER, lat REAL, long REAL, uploaded INTEGER );

CREATE TABLE summaries( date STRING NOT NULL, spent REAL NOT NULL, past_budget REAL NOT NULL );